sudo: required
language: go
cache:
  directories:
    - $HOME/.glide/cache
go:
  - 1.5
  - 1.6
  - 1.7rc6
  - tip
services:
  - docker
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.8.0
    - COMMIT=${TRAVIS_COMMIT::8}
    # Set higher timeouts for Travis
    - TEST_TIMEOUT_SCALE=20
before_install:
  - docker version
  - make install_docker_ci
install: make install_ci
script:
  - make test_ci
  - make cover_ci
  - make lint
  - make crossdock_ci
